### ISSUE TITLE
Consistent naming

### ISSUE THREAD

**Issue by rapgro** [ZZYZX/qparted#3]
You should change all occurence of "QtParted" into "QParted" to identicate a consequent fork.
- The application window title refers to "QtParted" instead of "Qparted". 
- Adjust the copyright and the about dialog box to honor the original work and identicate your fork.
- Icons in data sub directory should be renamed, too.
- Name the binary and manpage.

This is confusing.

**Comment by snshn** [comment]
Thank you for contributing, Raphael.

Pretty much I have just forked it for the personal use and hoped that more people would join in to help me with it later. Glad to see some interest in it.
Going to follow your tips and improve it once I get some time off my work.

**Comment by rapgro** [comment]
We are trying to package qparted for Fedora. So it would be nice to see any progress of this project. :+1:

**Comment by snshn** [comment]
Done, still need to replace "QtParted" with "QParted", remove the smileys from many code comment lines and translation strings, but overall it's much more QParted now.

I've been busy but now should have more time to make this thing more useful for our community.
I'd like to add you to the team in case you'd like to contribute.
Thank you once again and please excuse me for the delay, has really been out of time.

**Comment by rapgro** [comment]
Thanks for the fix.
